export interface WorkoutDetailInterface {
  id: number;
  workout_type_id: number;
  user_id: number;
  created_by: number;
  title: string;
  code: string | number;
  workout_day: string;
  workout_day_en: string | number;
  time_stamp: string | number;
  start_time: string | number;
  start_time_planned: string | number;
  completed: string | number;
  description: string | number;
  distance: string | number;
  distance_planned: string | number;
  total_time: string | number;
  total_time_planned: string | number;
  elapsed_time: string | number;
  power_average: string | number;
  heart_rate_minimum: string | number;
  heart_rate_maximum: string | number;
  heart_rate_average: string | number;
  work: string | number;
  calories: string | number;
  total_ascent: string | number;
  total_descent: string | number;
  calories_planned: string | number;
  np: string | number;
  tss_actual: string | number;
  tss_planned: string | number;
  atl: string | number;
  ctl: string | number;
  tsb: string | number;
  if_actual: string | number;
  vi: string | number;
  if_planned: string | number;
  rpe: string | number;
  feeling: string | number;
  tags: string | number;
  structure: string | number;
  fit_file: string | number;
  order_on_day: string | number;
  order_on_plan: string | number;
  created_at: string;
  updated_at: string;
}
